package com.shopwatch.api.mail;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;

@Component
public class MailSend {
	
	@Autowired
    public JavaMailSender emailSender;
	
	public void sendMailRegister(String email,String name) throws MessagingException {
		MimeMessage message = emailSender.createMimeMessage();
		 
        boolean multipart = true;
         
        MimeMessageHelper helper = new MimeMessageHelper(message, multipart, "utf-8");
         
        String htmlMsg = "<!doctype html>\r\n"
        		+ "<html lang=\"en-US\">\r\n"
        		+ "\r\n"
        		+ "<head>\r\n"
        		+ "    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\r\n"
        		+ "    <title>Reset Password Email Template</title>\r\n"
        		+ "    <meta name=\"description\" content=\"Reset Password Email Template.\">\r\n"
        		+ "    <style type=\"text/css\">\r\n"
        		+ "        a:hover {text-decoration: underline !important;}\r\n"
        		+ "    </style>\r\n"
        		+ "</head>\r\n"
        		+ "\r\n"
        		+ "<body marginheight=\"0\" topmargin=\"0\" marginwidth=\"0\" style=\"margin: 0px; background-color: #f2f3f8;\" leftmargin=\"0\">\r\n"
        		+ "<table cellspacing=\"0\" border=\"0\" cellpadding=\"0\" width=\"100%\" bgcolor=\"#f2f3f8\" style=\"\r\n"
        		+ "    @import url(https://fonts.googleapis.com/css?family=Rubik:300,400,500,700|Open+Sans:300,400,600,700);\r\n"
        		+ "    font-family: \"Times New Roman\", Times, serif;\r\n"
        		+ "  \">\r\n"
        		+ "  <tr>\r\n"
        		+ "    <td>\r\n"
        		+ "      <table style=\"background-color: #f2f3f8; max-width: 670px; margin: 0 auto\" width=\"100%\" border=\"0\" align=\"center\"\r\n"
        		+ "        cellpadding=\"0\" cellspacing=\"0\">\r\n"
        		+ "        <tr>\r\n"
        		+ "          <td style=\"height: 80px\">&nbsp;</td>\r\n"
        		+ "        </tr>\r\n"
        		+ "        <tr>\r\n"
        		+ "          <td style=\"text-align: center\">\r\n"
        		+ "            <a href=\"https://watchshop-44.web.app/\" title=\"logo\" target=\"_blank\">\r\n"
        		+ "              <img width=\"60\" src=\"https://i.ibb.co/zn8jkMT/logo.png\" title=\"logo\" alt=\"logo\" />\r\n"
        		+ "            </a>\r\n"
        		+ "          </td>\r\n"
        		+ "        </tr>\r\n"
        		+ "        <tr>\r\n"
        		+ "          <td style=\"height: 20px\">&nbsp;</td>\r\n"
        		+ "        </tr>\r\n"
        		+ "        <tr>\r\n"
        		+ "          <td>\r\n"
        		+ "            <table width=\"95%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"\r\n"
        		+ "                max-width: 670px;\r\n"
        		+ "                background: #fff;\r\n"
        		+ "                border-radius: 3px;\r\n"
        		+ "                text-align: center;\r\n"
        		+ "                -webkit-box-shadow: 0 6px 18px 0 rgba(0, 0, 0, 0.06);\r\n"
        		+ "                -moz-box-shadow: 0 6px 18px 0 rgba(0, 0, 0, 0.06);\r\n"
        		+ "                box-shadow: 0 6px 18px 0 rgba(0, 0, 0, 0.06);\r\n"
        		+ "              \">\r\n"
        		+ "              <tr>\r\n"
        		+ "                <td style=\"height: 40px\">&nbsp;</td>\r\n"
        		+ "              </tr>\r\n"
        		+ "              <tr>\r\n"
        		+ "                <td style=\"padding: 0 35px\">\r\n"
        		+ "                  <h1 style=\"\r\n"
        		+ "                      color: #1e1e2d;\r\n"
        		+ "                      font-weight: 500;\r\n"
        		+ "                      margin: 0;\r\n"
        		+ "                      font-size: 32px;\r\n"
        		+ "                      font-family: 'Rubik', sans-serif;\r\n"
        		+ "                    \">\r\n"
        		+ "                    Account Register Success !!!\r\n"
        		+ "                  </h1>\r\n"
        		+ "                  <span style=\"\r\n"
        		+ "                      display: inline-block;\r\n"
        		+ "                      vertical-align: middle;\r\n"
        		+ "                      margin: 29px 0 26px;\r\n"
        		+ "                      border-bottom: 1px solid #cecece;\r\n"
        		+ "                      width: 300px;\r\n"
        		+ "                    \"></span>\r\n"
        		+ "                   <p style=\"margin: 0px; font-size:20px;\">Hi, <span style=\"color:red;\"> "+name+" </span>.</p>\r\n"
        		+ "                  <span style=\"\r\n"
        		+ "                      display: inline-block;\r\n"
        		+ "                      vertical-align: middle;\r\n"
        		+ "                      margin: 29px 0 26px;\r\n"
        		+ "                      border-bottom: 1px solid #cecece;\r\n"
        		+ "                      width: 300px;\r\n"
        		+ "                    \"></span>\r\n"
        		+ "                  <p style=\"\r\n"
        		+ "                      color: gray;\r\n"
        		+ "                      font-size: 19px;\r\n"
        		+ "                      line-height: 24px;\r\n"
        		+ "                      margin: 0;\r\n"
        		+ "                    \">Watch-Shop: Best Price In Viet Nam.</p>\r\n"
        		+ "                   <p>[ FPT Polytechnic - Group 44 ]</p>\r\n"
        		+ "                  <a href=\"https://watchshop-44.web.app/index\" style=\"\r\n"
        		+ "                      background: #20e277;\r\n"
        		+ "                      text-decoration: none !important;\r\n"
        		+ "                      font-weight: 500;\r\n"
        		+ "                      margin-top: 35px;\r\n"
        		+ "                      color: #fff;\r\n"
        		+ "                      text-transform: uppercase;\r\n"
        		+ "                      font-size: 14px;\r\n"
        		+ "                      padding: 10px 24px;\r\n"
        		+ "                      display: inline-block;\r\n"
        		+ "                      border-radius: 50px;\r\n"
        		+ "                    \">Login</a>\r\n"
        		+ "                </td>\r\n"
        		+ "              </tr>\r\n"
        		+ "              <tr>\r\n"
        		+ "                <td style=\"height: 40px\">&nbsp;</td>\r\n"
        		+ "              </tr>\r\n"
        		+ "            </table>\r\n"
        		+ "          </td>\r\n"
        		+ "        </tr>\r\n"
        		+ "\r\n"
        		+ "        <tr>\r\n"
        		+ "          <td style=\"height: 20px\">&nbsp;</td>\r\n"
        		+ "        </tr>\r\n"
        		+ "        <tr>\r\n"
        		+ "          <td style=\"text-align: center\">\r\n"
        		+ "            <p style=\"\r\n"
        		+ "                font-size: 14px;\r\n"
        		+ "                color: rgba(69, 80, 86, 0.7411764705882353);\r\n"
        		+ "                line-height: 18px;\r\n"
        		+ "                margin: 0 0 0;\r\n"
        		+ "              \">\r\n"
        		+ "              &copy; <strong>https://watchshop-44.web.app/</strong>\r\n"
        		+ "            </p>\r\n"
        		+ "          </td>\r\n"
        		+ "        </tr>\r\n"
        		+ "        <tr>\r\n"
        		+ "          <td style=\"height: 80px\">&nbsp;</td>\r\n"
        		+ "        </tr>\r\n"
        		+ "      </table>\r\n"
        		+ "    </td>\r\n"
        		+ "  </tr>\r\n"
        		+ "</table>\r\n"
        		+ "</body>\r\n"
        		+ "</html>";
         
        message.setContent(htmlMsg, "text/html");
         
        helper.setTo(email);
         
        helper.setSubject("Đăng ký Tài Khoản WatchShop Thành Công!");
         
     
        this.emailSender.send(message);
	}
	
	public void sendMailChangeStatusBill(String email,int status_bill,String name) throws MessagingException {
		String trangThai = "";
		if (status_bill == 0) {
			trangThai = "CHO_XAC_NHAN";
		} else if (status_bill == 1) {
			trangThai = "DONG_GOI";
		} else if (status_bill == 2) {
			trangThai = "DANG_GIAO_HANG";
		} else if (status_bill == 3) {
			trangThai = "DA_THANH_TOAN";
		} else if (status_bill == 4) {
			trangThai = "DA_HUY";
		} 
		
		MimeMessage message = emailSender.createMimeMessage();
		 
        boolean multipart = true;
         
        MimeMessageHelper helper = new MimeMessageHelper(message, multipart, "utf-8");
         
        String htmlMsg = "<table\r\n"
        		+ "  style=\"\r\n"
        		+ "    font-size: 16px;\r\n"
        		+ "    font-family: Arial, Tahoma, Verdana, Geneva, sans-serif;\r\n"
        		+ "    line-height: 20px;\r\n"
        		+ "    color: #000000;\r\n"
        		+ "  \"\r\n"
        		+ "  border=\"0\"\r\n"
        		+ "  width=\"100%\"\r\n"
        		+ "  cellspacing=\"0\"\r\n"
        		+ "  cellpadding=\"0\"\r\n"
        		+ "  bgcolor=\"#e8e8e8\"\r\n"
        		+ ">\r\n"
        		+ "  <tbody>\r\n"
        		+ "    <tr>\r\n"
        		+ "      <td align=\"center\">\r\n"
        		+ "        <table\r\n"
        		+ "          style=\"margin: 0 auto\"\r\n"
        		+ "          border=\"0\"\r\n"
        		+ "          width=\"600\"\r\n"
        		+ "          cellspacing=\"0\"\r\n"
        		+ "          cellpadding=\"0\"\r\n"
        		+ "        >\r\n"
        		+ "          <tbody>\r\n"
        		+ "            <tr>\r\n"
        		+ "              <td\r\n"
        		+ "                style=\"padding-top: 25px; padding-bottom: 20px\"\r\n"
        		+ "                align=\"center\"\r\n"
        		+ "              >\r\n"
        		+ "                <img\r\n"
        		+ "                  style=\"max-height: 33px\"\r\n"
        		+ "                  src=\"https://i.ibb.co/zn8jkMT/logo.png\"\r\n"
        		+ "                  alt=\"\"\r\n"
        		+ "                  height=\"33\"\r\n"
        		+ "                />\r\n"
        		+ "              </td>\r\n"
        		+ "            </tr>\r\n"
        		+ "            <tr>\r\n"
        		+ "              <td>\r\n"
        		+ "                <table\r\n"
        		+ "                  id=\"header\"\r\n"
        		+ "                  style=\"color: #ffffff\"\r\n"
        		+ "                  border=\"0\"\r\n"
        		+ "                  width=\"100%\"\r\n"
        		+ "                  cellspacing=\"0\"\r\n"
        		+ "                  cellpadding=\"0\"\r\n"
        		+ "                  bgcolor=\"#55cf31\"\r\n"
        		+ "                >\r\n"
        		+ "                  <tbody>\r\n"
        		+ "                    <tr>\r\n"
        		+ "                      <td\r\n"
        		+ "                        style=\"\r\n"
        		+ "                          font-size: 20px;\r\n"
        		+ "                          font-family: Arial, Tahoma, Verdana, Geneva,\r\n"
        		+ "                            sans-serif;\r\n"
        		+ "                          line-height: 26px;\r\n"
        		+ "                          padding: 21px 10px 20px 30px;\r\n"
        		+ "                        \"\r\n"
        		+ "                        valign=\"middle\"\r\n"
        		+ "                        width=\"75%\"\r\n"
        		+ "                      >\r\n"
        		+ "                        <span style=\"vertical-align: inherit\"\r\n"
        		+ "                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                            >Your Order</span\r\n"
        		+ "                          ></span\r\n"
        		+ "                        >\r\n"
        		+ "                      </td>\r\n"
        		+ "                      <td\r\n"
        		+ "                        style=\"padding: 8px 30px 8px 10px\"\r\n"
        		+ "                        align=\"right\"\r\n"
        		+ "                        valign=\"middle\"\r\n"
        		+ "                        width=\"25%\"\r\n"
        		+ "                      >\r\n"
        		+ "                        <img\r\n"
        		+ "                          style=\"border: 0; vertical-align: top\"\r\n"
        		+ "                          src=\"https://i.ibb.co/zn8jkMT/logo.png\"\r\n"
        		+ "                          width=\"25\"\r\n"
        		+ "                          height=\"27\"\r\n"
        		+ "                        />\r\n"
        		+ "                      </td>\r\n"
        		+ "                    </tr>\r\n"
        		+ "                  </tbody>\r\n"
        		+ "                </table>\r\n"
        		+ "              </td>\r\n"
        		+ "            </tr>\r\n"
        		+ "            <tr>\r\n"
        		+ "              <td style=\"padding: 35px 29px 45px 29px\" bgcolor=\"#ffffff\">\r\n"
        		+ "                <table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
        		+ "                  <tbody>\r\n"
        		+ "                    <tr>\r\n"
        		+ "                      <td\r\n"
        		+ "                        style=\"\r\n"
        		+ "                          font-family: Arial, Tahoma, Verdana, Geneva,\r\n"
        		+ "                            sans-serif;\r\n"
        		+ "                          padding-bottom: 15px;\r\n"
        		+ "                        \"\r\n"
        		+ "                      >\r\n"
        		+ "                        <span style=\"vertical-align: inherit\"\r\n"
        		+ "                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                            >Hello, [ "+name+" ]!</span\r\n"
        		+ "                          ></span\r\n"
        		+ "                        >\r\n"
        		+ "                      </td>\r\n"
        		+ "                    </tr>\r\n"
        		+ "                    <tr>\r\n"
        		+ "                      <td\r\n"
        		+ "                        style=\"\r\n"
        		+ "                          font-family: Arial, Tahoma, Verdana, Geneva,\r\n"
        		+ "                            sans-serif;\r\n"
        		+ "                          padding-bottom: 34px;\r\n"
        		+ "                        \"\r\n"
        		+ "                      >\r\n"
        		+ "                        <span style=\"vertical-align: inherit\"\r\n"
        		+ "                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                            >You receive notifications about the status of your orders on the Watch-Shop.</span\r\n"
        		+ "                          ></span\r\n"
        		+ "                        >\r\n"
        		+ "                      </td>\r\n"
        		+ "                    </tr>\r\n"
        		+ "                    <tr>\r\n"
        		+ "                      <td>\r\n"
        		+ "                        <table\r\n"
        		+ "                          border=\"0\"\r\n"
        		+ "                          width=\"100%\"\r\n"
        		+ "                          cellspacing=\"0\"\r\n"
        		+ "                          cellpadding=\"0\"\r\n"
        		+ "                        >\r\n"
        		+ "                          <tbody>\r\n"
        		+ "                            <tr>\r\n"
        		+ "                              <td\r\n"
        		+ "                                style=\"\r\n"
        		+ "                                  padding-top: 5px;\r\n"
        		+ "                                  padding-left: 5px;\r\n"
        		+ "                                  padding-right: 25px;\r\n"
        		+ "                                \"\r\n"
        		+ "                                align=\"center\"\r\n"
        		+ "                                valign=\"top\"\r\n"
        		+ "                                width=\"168\"\r\n"
        		+ "                              >\r\n"
        		+ "                                <img\r\n"
        		+ "                                  style=\"border: 0; vertical-align: top\"\r\n"
        		+ "                                  src=\"https://i.ibb.co/zn8jkMT/logo.png\"\r\n"
        		+ "                                  width=\"112\"\r\n"
        		+ "                                  height=\"146\"\r\n"
        		+ "                                />\r\n"
        		+ "                              </td>\r\n"
        		+ "                              <td valign=\"top\">\r\n"
        		+ "                                <table\r\n"
        		+ "                                  border=\"0\"\r\n"
        		+ "                                  width=\"100%\"\r\n"
        		+ "                                  cellspacing=\"0\"\r\n"
        		+ "                                  cellpadding=\"0\"\r\n"
        		+ "                                >\r\n"
        		+ "                                  <tbody>\r\n"
        		+ "                                    <tr>\r\n"
        		+ "                                      <td\r\n"
        		+ "                                        style=\"\r\n"
        		+ "                                          font-family: Arial, Tahoma, Verdana,\r\n"
        		+ "                                            Geneva, sans-serif;\r\n"
        		+ "                                          padding-bottom: 21px;\r\n"
        		+ "                                        \"\r\n"
        		+ "                                      >\r\n"
        		+ "                                        <strong style=\"color: #007aff\"\r\n"
        		+ "                                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                                            ><span\r\n"
        		+ "                                              style=\"vertical-align: inherit\"\r\n"
        		+ "                                              >[ Notification System ]</span\r\n"
        		+ "                                            ></span\r\n"
        		+ "                                          ></strong\r\n"
        		+ "                                        >\r\n"
        		+ "                                      </td>\r\n"
        		+ "                                    </tr>\r\n"
        		+ "                                    <tr>\r\n"
        		+ "                                      <td\r\n"
        		+ "                                        id=\"msg-title\"\r\n"
        		+ "                                        style=\"\r\n"
        		+ "                                          font-family: Arial, Tahoma, Verdana,\r\n"
        		+ "                                            Geneva, sans-serif;\r\n"
        		+ "                                          padding-bottom: 6px;\r\n"
        		+ "                                        \"\r\n"
        		+ "                                      >\r\n"
        		+ "                                        <strong\r\n"
        		+ "                                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                                            ><span\r\n"
        		+ "                                              style=\"vertical-align: inherit\"\r\n"
        		+ "                                              >Message</span\r\n"
        		+ "                                            ></span\r\n"
        		+ "                                          ></strong\r\n"
        		+ "                                        >\r\n"
        		+ "                                      </td>\r\n"
        		+ "                                    </tr>\r\n"
        		+ "                                    <tr>\r\n"
        		+ "                                      <td\r\n"
        		+ "                                        id=\"msg-text\"\r\n"
        		+ "                                        style=\"\r\n"
        		+ "                                          font-family: Arial, Tahoma, Verdana,\r\n"
        		+ "                                            Geneva, sans-serif;\r\n"
        		+ "                                          padding-bottom: 20px;\r\n"
        		+ "                                        \"\r\n"
        		+ "                                      >\r\n"
        		+ "                                        <span style=\"vertical-align: inherit\"\r\n"
        		+ "                                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                                            >STATUS: <span style=\"color:red;\">[ "+trangThai+" ]</span></span\r\n"
        		+ "                                          ></span\r\n"
        		+ "                                        >\r\n"
        		+ "                                      </td>\r\n"
        		+ "                                    </tr>\r\n"
        		+ "                                    <tr>\r\n"
        		+ "                                      <td style=\"padding-bottom: 14px\">\r\n"
        		+ "                                        <table\r\n"
        		+ "                                          id=\"avatar-div\"\r\n"
        		+ "                                          style=\"\r\n"
        		+ "                                            border-radius: 100%;\r\n"
        		+ "                                            overflow: hidden;\r\n"
        		+ "                                          \"\r\n"
        		+ "                                          border=\"0\"\r\n"
        		+ "                                          width=\"63\"\r\n"
        		+ "                                          cellspacing=\"0\"\r\n"
        		+ "                                          cellpadding=\"0\"\r\n"
        		+ "                                        >\r\n"
        		+ "                                          \r\n"
        		+ "                                        </table>\r\n"
        		+ "                                      </td>\r\n"
        		+ "                                    </tr>\r\n"
        		+ "                                    <tr>\r\n"
        		+ "                                      <td\r\n"
        		+ "                                        style=\"\r\n"
        		+ "                                          font-size: 14px;\r\n"
        		+ "                                          font-family: Arial, Tahoma, Verdana,\r\n"
        		+ "                                            Geneva, sans-serif;\r\n"
        		+ "                                        \"\r\n"
        		+ "                                      >\r\n"
        		+ "                                        <span style=\"vertical-align: inherit\"\r\n"
        		+ "                                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                                            >[ From: watchshop-44 ]</span\r\n"
        		+ "                                          ></span\r\n"
        		+ "                                        >\r\n"
        		+ "                                      </td>\r\n"
        		+ "                                    </tr>\r\n"
        		+ "                                    <tr>\r\n"
        		+ "                                      <td\r\n"
        		+ "                                        style=\"\r\n"
        		+ "                                          font-size: 14px;\r\n"
        		+ "                                          font-family: Arial, Tahoma, Verdana,\r\n"
        		+ "                                            Geneva, sans-serif;\r\n"
        		+ "                                        \"\r\n"
        		+ "                                      >\r\n"
        		+ "                                        <span style=\"vertical-align: inherit\"\r\n"
        		+ "                                          ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                                            >[ api.watchshop247@gmail.com\r\n"
        		+ " ]</span\r\n"
        		+ "                                          ></span\r\n"
        		+ "                                        >\r\n"
        		+ "                                      </td>\r\n"
        		+ "                                    </tr>\r\n"
        		+ "                                  </tbody>\r\n"
        		+ "                                </table>\r\n"
        		+ "                              </td>\r\n"
        		+ "                            </tr>\r\n"
        		+ "                          </tbody>\r\n"
        		+ "                        </table>\r\n"
        		+ "                      </td>\r\n"
        		+ "                    </tr>\r\n"
        		+ "                  </tbody>\r\n"
        		+ "                </table>\r\n"
        		+ "              </td>\r\n"
        		+ "            </tr>\r\n"
        		+ "            <tr>\r\n"
        		+ "              <td\r\n"
        		+ "                style=\"\r\n"
        		+ "                  font-size: 11px;\r\n"
        		+ "                  font-family: Arial, Tahoma, Verdana, Geneva, sans-serif;\r\n"
        		+ "                  line-height: 13px;\r\n"
        		+ "                  color: #939393;\r\n"
        		+ "                  padding: 29px 10px 5px 10px;\r\n"
        		+ "                \"\r\n"
        		+ "                align=\"center\"\r\n"
        		+ "              >\r\n"
        		+ "                <span style=\"vertical-align: inherit\"\r\n"
        		+ "                  ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                    >Email n&agrave;y được tạo tự động. </span\r\n"
        		+ "                  ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                    >Kh&ocirc;ng trả lời v&igrave; hộp thư đến kh&ocirc;ng được\r\n"
        		+ "                    gi&aacute;m s&aacute;t.</span\r\n"
        		+ "                  ></span\r\n"
        		+ "                >\r\n"
        		+ "              </td>\r\n"
        		+ "            </tr>\r\n"
        		+ "            <tr>\r\n"
        		+ "              <td\r\n"
        		+ "                style=\"\r\n"
        		+ "                  font-size: 11px;\r\n"
        		+ "                  font-family: Arial, Tahoma, Verdana, Geneva, sans-serif;\r\n"
        		+ "                  line-height: 13px;\r\n"
        		+ "                  color: #939393;\r\n"
        		+ "                  padding-left: 10px;\r\n"
        		+ "                  padding-right: 10px;\r\n"
        		+ "                  padding-bottom: 50px;\r\n"
        		+ "                \"\r\n"
        		+ "                align=\"center\"\r\n"
        		+ "              >\r\n"
        		+ "                <span style=\"vertical-align: inherit\"\r\n"
        		+ "                  ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                    >&copy; [COMPANY_COPYRIGHTS]. </span\r\n"
        		+ "                  ><span style=\"vertical-align: inherit\"\r\n"
        		+ "                    >Đ&atilde; đăng k&yacute; Bản quyền.</span\r\n"
        		+ "                  ></span\r\n"
        		+ "                >\r\n"
        		+ "              </td>\r\n"
        		+ "            </tr>\r\n"
        		+ "          </tbody>\r\n"
        		+ "        </table>\r\n"
        		+ "      </td>\r\n"
        		+ "    </tr>\r\n"
        		+ "  </tbody>\r\n"
        		+ "</table>\r\n"
        		+ "";
         
        message.setContent(htmlMsg, "text/html");
         
        helper.setTo(email);
         
        helper.setSubject("Thông Báo Tình Trạng Đơn Hàng!");
         
     
        this.emailSender.send(message);
	}
	
	
	
}
